const CONFIG = Object.freeze({
  SHEET_DATA: "Data",
  SHEET_COMPANY: "Company",
  SHEET_LOGS: "Logs",
  SHEET_STATE_LOG: "StateLog",

  API_KEY_CELL_A1: "K2",
  NEWS_FROM_EPOCH: 1748879253,

  SNAPSHOT_PROPERTY_KEY: "PAID_TRAINS_LEFT_SNAPSHOT",
  STATE_PROPERTY_KEY: "PAID_TRAINS_STATE_V2",

  EMPLOYEE_TABLE_FIRST_ROW: 2,
  EMPLOYEE_TABLE_LAST_ROW: 100,
  STATUS_CELL_A1: "A15",
  STATUS_ROW: 15,

  // Employee table columns imported from Torn (A:C)
  COL_EMPLOYEE_NAME: 1,
  COL_LAST_ACTION: 2,
  COL_WAGE: 3,

  // Computed output columns (D:I)
  COL_PAID_TRAINS_LEFT: 4,
  COL_EFFECTIVE_PAYMENT_DATE: 5,
  COL_EFFECTIVE_PAY_AMOUNT: 6,
  COL_EFFECTIVE_TRAIN_VALUE: 7,
  COL_TRAINS_USED_SINCE_PAYMENT: 8,
  COL_FIRST_TRAINING_LOG_ROW: 9,

  // Payment input table (L:O)
  COL_PAYTABLE_NAME: 12,
  COL_PAYTABLE_DATE: 13,
  COL_PAYTABLE_AMOUNT: 14,
  COL_PAYTABLE_TRAIN_VALUE: 15,

  DEBUG: true,
  DEBUG_MAX_MATCH_LINES_PER_EMPLOYEE: 25,

  ALLOWED_SPREADSHEET_ID: "1INRmJohNQME_1Y449FCfQr9hazdN3tUp7yoEOzvYYNA"
});