// Generate a report with an OpenRouter free model.
// Usage:  OPENROUTER_API_KEY=sk-or-... node AITools/openrouter-report.mjs [facts.md] [out.md]
// Falls back through MODELS in order on 429 / 5xx / empty reply.

import { readFileSync, writeFileSync } from "node:fs";

const KEY = process.env.OPENROUTER_API_KEY;
if (!KEY) {
  console.error("OPENROUTER_API_KEY is not set.");
  process.exit(1);
}

const MODELS = [
  "z-ai/glm-5.2:free",
  "nvidia/nemotron-3-ultra-550b-a55b:free",
  "google/gemma-4-31b-it:free",
  "nvidia/nemotron-3-super-120b-a12b:free",
];

const factsPath = process.argv[2] || "AITools/free-ai-providers-facts.md";
const outPath = process.argv[3] || "AITools/free-ai-providers-report.md";
const facts = readFileSync(factsPath, "utf8");

const system =
  "You write short, factual comparison reports. Use only the facts given. " +
  "Do not invent numbers. Plain hyphens, no em dashes. Markdown. Under 400 words.";

const user =
  "Write a report answering: which free AI API provider is best today, " +
  "where best means the fewest rate-limit hits in normal use (not blocked every 2 prompts)?\n\n" +
  "Structure: one-line verdict, a table of providers with RPM / per-day limits, " +
  "a short pick-by-use-case list, caveats, and a sources list.\n\n" +
  "FACTS:\n" + facts;

async function call(model) {
  const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: "Bearer " + KEY,
      "Content-Type": "application/json",
      "HTTP-Referer": "https://github.com/ionutfilea/torn",
      "X-Title": "Torn AITools report",
    },
    body: JSON.stringify({
      model,
      temperature: 0.2,
      messages: [
        { role: "system", content: system },
        { role: "user", content: user },
      ],
    }),
  });
  const status = res.status;
  const json = await res.json().catch(() => ({}));
  const text = json?.choices?.[0]?.message?.content?.trim();
  return { status, text, error: json?.error?.message };
}

for (const model of MODELS) {
  process.stderr.write("Trying " + model + " ... ");
  const r = await call(model);
  if (r.status === 200 && r.text) {
    console.error("ok");
    const header =
      "<!-- generated by " + model + " via OpenRouter -->\n\n";
    writeFileSync(outPath, header + r.text + "\n");
    console.log(r.text);
    console.error("\nSaved to " + outPath);
    process.exit(0);
  }
  console.error("failed (" + r.status + ") " + (r.error || "empty reply"));
}
console.error("All models failed.");
process.exit(2);
